# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
